### GET http://localhost:3001/adios

###
GET http://localhost:3001/api/currency

### Get Currency by ID
GET http://localhost:3001/api/currency/1

### Post Currency
POST http://localhost:3001/api/currency
Content-Type: application/json

{
  "currencyCode": "NGN",
  "countryId": 13,
  "conversionRate": 98
}

### Put Currency by ID
PUT http://localhost:3001/api/currency/5/9.99

### Delete Currency by ID
DELETE http://localhost:3001/api/currency/1

### Unknown Endpoint
GET http://localhost:3001/api/currency

### GET (cCroutes)
GET http://localhost:3001/currency-countryName  

### GET (crudCountry)
GET http://localhost:3001/api/country 

### POST (crudCountry)
POST http://localhost:3001/api/country
Content-Type: application/json

{
  "name" : "Iraq"
}

### DELETE (crudCountry)
DELETE http://localhost:3001/api/country/32
