GET http://localhost:3002/api/currency/

### Get Currency by ID
GET http://localhost:3002/api/currency/1 

### Post Currency
POST http://localhost:3002/api/currency
Content-Type: application/json

{
  "currencyCode": "KWD",
  "country": "Kuwait",
  "conversionRate": 2
}

### Put Currency by ID
PUT http://localhost:3002/api/currency/1/9.0
Content-Type: application/json

{
  "currencyCode": "KWD",
  "country": "Kuwait",
  "conversionRate": 9.0
}

### Delete Currency by ID
DELETE http://localhost:3002/api/currency/2

### Unknown Endpoint
GET http://localhost:3002/api/currency
